//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPractise
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyPractiseDBEntities : DbContext
    {
        public MyPractiseDBEntities()
            : base("name=MyPractiseDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ReaderDetails> ReaderDetails { get; set; }
        public DbSet<ReaderModels> ReaderModels { get; set; }
        public DbSet<Participant> Participants { get; set; }
        public DbSet<ReaderReviewModel> ReaderReviewModels { get; set; }
        public DbSet<Registration> Registrations { get; set; }
        public DbSet<XEvent> XEvents { get; set; }
    }
}
