//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPractise
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReaderModels
    {
        public ReaderModels()
        {
            this.ReaderDetails = new HashSet<ReaderDetails>();
        }
    
        public int Id { get; set; }
        public string ReaderName { get; set; }
        public string IP { get; set; }
        public int Port { get; set; }
        public int ConnectionStatus { get; set; }
        public string ReaderType { get; set; }
    
        public virtual ICollection<ReaderDetails> ReaderDetails { get; set; }
    }
}
